### ISSUE TITLE
Back Key exits

### ISSUE THREAD

**Issue by TQMatvey** [sillygir1/flipperzero-fnaf#1]
Hello! i'd like to start off by saying this is THE COOLEST game for flipper zero, i play all FNAF games, and i love it
but i'd suggest a small improvement, back should exit the camera instead of exiting the game, i keep accidentally pressing back and failing lol, long back should exit the game imo, but thanks for making this in the first place!

**Comment by sillygir1** [comment]
Fixed, you can get latest FAP in actions if you want it right now, hopefully update will be soon in catalog too.
