### ISSUE TITLE
Game Crashes on Jumpscare

### ISSUE THREAD

**Issue by Contr0versy** [sillygir1/flipperzero-fnaf#2]
Current version of the game crashes on the newest firmware (0.97.1)

I'll take a look to see if I can see any issues with the code, but I'm not too experienced with the structure of flipper applications, so I doubt I'll find anything.

**Comment by RogueMaster** [comment]
Works for me, try this code: https://github.com/RogueMaster/flipperzero-firmware-wPlugins/tree/420/applications/external/fivenightsatflippers

**Comment by sillygir1** [comment]
Does it only crash on jumpscares? Are there any other scenarios where it crashes too? Tested a bit, works fine for me on 0.97.1. Can you maybe try using another sd card? Also, can you please show me logs (on "debug" level) of when the game starts?
To read logs you can use cli on lab.flipper.net (if your browser supports Web Serial API) or any serial terminal (baudrate is 230400) and send `log debug` command. After this you should start the game. It will also be nice to see logs of crashes. 
Edit: You can also use `fbt cli` or `ufbt cli` to access flipper's cli.
