### ISSUE TITLE
Update the Five Nights at Flipper's app for the SDK version 0.98.1-rc f7

### ISSUE THREAD

**Issue by furippa** [sillygir1/flipperzero-fnaf#3]
Hello! Your Five Nights at Flipper's app version 1.1 fails to build with the SDK version 0.98.1-rc f7. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/64f1b8a913043e71ea766881/page)

**Comment by sillygir1** [comment]
Done!
