### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by leedave** [sillygir1/flipperzero-fnaf#4]
Hi there 

Been looking at the game, controls work and it seems like an interesting concept. But I cannot get the grasp on what I'm supposed to be doing. Watching the FNAF movie didn't help either. 

Could you take some time to write instructions into your README.md ?

**Comment by sillygir1** [comment]
Well, this is a demake of the original FNAF game, so you can find info about it all over the internet. But you're right, i should write a better description, thanks.

**Comment by sillygir1** [comment]
Finally made a bare minimum description for catalog.
