### ISSUE TITLE
Looking issue

### ISSUE THREAD

**Issue by Carrot7353** [sillygir1/flipperzero-fnaf#5]
When you look right the screen turn blank
Please help me
![IMG_20240523_170651](https://github.com/sillygir1/flipperzero-fnaf/assets/77265129/b59abcca-fd94-4cdb-8763-1b0789e8f969)
![IMG_20240523_170639](https://github.com/sillygir1/flipperzero-fnaf/assets/77265129/bb4b9f84-5cd8-4e14-9de5-dde51cc32cea)
![IMG_20240523_170641](https://github.com/sillygir1/flipperzero-fnaf/assets/77265129/eaa5eb81-c586-4e97-9a23-95f7c5870d9d)

**Comment by sillygir1** [comment]
This is somehow broken on the last firmwares (i tested it on 0.97.1 and it worked). I'll get to it when i'll have free time.

**Comment by Carrot7353** [comment]
Thanks 🙏

**Comment by sillygir1** [comment]
Fixed, you can get the latest fap in actions rn or wait till it'll be updated in catalog (i'll make a PR with new version soon).
